name: wave
description: Widget for displaying waves with custom color, duration, floating and blur effects.
version: 0.1.1
homepage: https://github.com/i-protoss/wave

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter